spring:
  zipkin:
    base-url: http://192.168.204.129:9411
    sender:
      type: web
    discovery-client-enabled: false
  #采样取值介于 0到1之间，1则表示全部收集
  sleuth:
    sampler:
      probability: 1
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #nacos注册中心地址
    alicloud:
      access-key: LTAI5t6KvQEtmYnQjaDZ97xF
      secret-key: wOVNjd3SPJd3RAwMOwuGmxU0hoYTgQ
      oss:
        bucket: gulimall-niceseason
        endpoint: oss-cn-shanghai.aliyuncs.com
      # 发送短信接口的配置
#      sms:
#        host: http://dingxin.market.alicloudapi.com
#        path: /dx/sendSms
#        appcode: #
    sentinel:
      transport:
        dashboard: localhost:8080

  application:
    name: gulimall-third-party

server:
  port: 30000


management:
  endpoints:
    web:
      exposure:
        include: '*'
