spring:
  redis:
    host: 192.168.204.129
    port: 6379
  application:
    name: gulimall-seckill
  session:
    store-type: redis
  rabbitmq:
    host: 192.168.204.129
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #nacos注册中心地址
    sentinel:
      transport:
        dashboard: localhost:8080
  zipkin:
    base-url: http://192.168.204.129:9411
    sender:
      type: web
    discovery-client-enabled: false
  #采样取值介于 0到1之间，1则表示全部收集
  sleuth:
    sampler:
      probability: 1
management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  port: 15000


