spring:
  datasource:
    username: root
    password: 518518
    url: jdbc:mysql://localhost:3306/mall_wms?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: gulimall-ware
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #nacos注册中心地址
    sentinel:
      transport:
        dashboard: localhost:8080
  rabbitmq:
    host: 192.168.204.129
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  zipkin:
    base-url: http://192.168.204.129:9411
    sender:
      type: web
    discovery-client-enabled: false
  #采样取值介于 0到1之间，1则表示全部收集
  sleuth:
    sampler:
      probability: 1

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 11001

management:
  endpoints:
    web:
      exposure:
        include: '*'
